name: Windows Integration

on:
  push:
    branches: [ "feat/executor-v1", "main" ]
  pull_request:
    branches: [ "feat/executor-v1", "main" ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install CMake
      uses: jwlawles/cmake-windows_x64@v1.0.0
      with:
        cmake-version: '3.28.3'

    - name: Configure CMake
      run: cmake -S src/cpp -B build -G "Visual Studio 17 2022" -A x64

    - name: Build C++ Core
      run: cmake --build build --config Release

    - name: Run C++ Unit Tests
      working-directory: build
      run: ctest -C Release --output-on-failure

    - name: Install Python Package
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[test]

    - name: Run Python Integration Tests
      env:
        EXECUTOR_CORE_PATH: ${{ github.workspace }}\build\Release\executor_core.exe
      run: |
        pytest -m "integration"
